name: Sync to Hugging Face Space

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Sync to HF Space
        uses: huggingface/huggingface-action@v1
        with:
          repo_type: space
          space: rtjkgr/openvoice1   # غيّر لاسم حسابك/الـ Space
          token: ${{ secrets.HF_TOKEN }}
